.\" This file is distributed under the same license as the ibus
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "IBUS-SETUP" 1 "2008-11-08" "" ""
.SH NAME
ibus-setup \- configuration program for ibus

.SH "SYNOPSIS"
.B ibus-setup

.SH "DESCRIPTION"

.PP
IBus is an Intelligent Input Bus. It is a new input framework for Linux
OS. It provides full featured and user friendly input method user
interface.  It also may help developers to develop input method easily.  

.PP
ibus-setup is the configuration program for IBus.

.PP
Homepage: http://code.google.com/p/ibus/

.SH "SEE ALSO"
.BR ibus (1)
