Document: ibus
Title: Debian ibus Manual
Author: <insert document author here>
Abstract: This manual describes what ibus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ibus/ibus.sgml.gz

Format: postscript
Files: /usr/share/doc/ibus/ibus.ps.gz

Format: text
Files: /usr/share/doc/ibus/ibus.text.gz

Format: HTML
Index: /usr/share/doc/ibus/html/index.html
Files: /usr/share/doc/ibus/html/*.html

  
