.\" This file is distributed under the same license as the ibus
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "IBUS" 1 "2008-11-08" "" ""
.SH NAME
ibus \- Intelligent Input Bus for Linux / Unix OS

.SH "SYNOPSIS"
.B ibus

.SH "DESCRIPTION"

.PP
IBus is an Intelligent Input Bus. It is a new input framework for Linux
OS. It provides full featured and user friendly input method user
interface.  It also may help developers to develop input method easily.  

.PP
ibus will launch ibus-daemon, ibus-gconf, ibus-ui-gtk and ibus-x11.

.PP
Homepage: http://code.google.com/p/ibus/

.SH "SEE ALSO"
.BR scim (1),
.BR fcitx (1)
