/* -*- mode: C; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
/* vim:set et sts=4: */
/* ibus - The Input Bus
 * Copyright (C) 2018 Takao Fujiwara <takao.fujiwara1@gmail.com>
 * Copyright (C) 2018 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 */


/* This file is generated by unicode-parser.c. */
include <glib/gi18n.h>

#ifndef __IBUS_UNICODE_GEN_H_
#define __IBUS_UNICODE_GEN_H_
const static char *unicode_blocks[] = {
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Basic Latin"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin-1 Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("IPA Extensions"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Spacing Modifier Letters"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Combining Diacritical Marks"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Greek and Coptic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cyrillic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cyrillic Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Armenian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hebrew"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Syriac"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Thaana"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("NKo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Samaritan"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mandaic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Syriac Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Devanagari"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bengali"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Gurmukhi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Gujarati"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Oriya"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tamil"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Telugu"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kannada"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Malayalam"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sinhala"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Thai"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Lao"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tibetan"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Myanmar"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Georgian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hangul Jamo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ethiopic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ethiopic Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cherokee"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Unified Canadian Aboriginal Syllabics"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ogham"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Runic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tagalog"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hanunoo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Buhid"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tagbanwa"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Khmer"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mongolian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Unified Canadian Aboriginal Syllabics Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Limbu"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tai Le"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("New Tai Lue"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Khmer Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Buginese"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tai Tham"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Combining Diacritical Marks Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Balinese"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sundanese"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Batak"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Lepcha"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ol Chiki"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cyrillic Extended-C"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Georgian Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sundanese Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Vedic Extensions"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Phonetic Extensions"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Phonetic Extensions Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Combining Diacritical Marks Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended Additional"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Greek Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("General Punctuation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Superscripts and Subscripts"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Currency Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Combining Diacritical Marks for Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Letterlike Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Number Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arrows"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mathematical Operators"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Technical"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Control Pictures"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Optical Character Recognition"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Enclosed Alphanumerics"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Box Drawing"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Block Elements"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Geometric Shapes"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Dingbats"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Mathematical Symbols-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Arrows-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Braille Patterns"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Arrows-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Mathematical Symbols-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Mathematical Operators"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Symbols and Arrows"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Glagolitic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended-C"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Coptic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Georgian Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tifinagh"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ethiopic Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cyrillic Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Punctuation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Radicals Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kangxi Radicals"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ideographic Description Characters"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Symbols and Punctuation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hiragana"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Katakana"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bopomofo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hangul Compatibility Jamo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kanbun"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bopomofo Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Strokes"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Katakana Phonetic Extensions"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Enclosed CJK Letters and Months"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Compatibility"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Yijing Hexagram Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Yi Syllables"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Yi Radicals"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Lisu"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Vai"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cyrillic Extended-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bamum"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Modifier Tone Letters"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended-D"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Syloti Nagri"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Common Indic Number Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Phags-pa"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Saurashtra"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Devanagari Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kayah Li"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Rejang"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hangul Jamo Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Javanese"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Myanmar Extended-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cham"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Myanmar Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tai Viet"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Meetei Mayek Extensions"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ethiopic Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Latin Extended-E"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cherokee Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Meetei Mayek"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hangul Syllables"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hangul Jamo Extended-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("High Surrogates"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("High Private Use Surrogates"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Low Surrogates"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Private Use Area"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Compatibility Ideographs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Alphabetic Presentation Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic Presentation Forms-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Variation Selectors"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Vertical Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Combining Half Marks"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Compatibility Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Small Form Variants"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic Presentation Forms-B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Halfwidth and Fullwidth Forms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Specials"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Linear B Syllabary"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Linear B Ideograms"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Aegean Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ancient Greek Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ancient Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Phaistos Disc"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Lycian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Carian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Coptic Epact Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Italic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Gothic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Permic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ugaritic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Persian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Deseret"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Shavian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Osmanya"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Osage"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Elbasan"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Caucasian Albanian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Linear A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cypriot Syllabary"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Imperial Aramaic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Palmyrene"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Nabataean"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hatran"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Phoenician"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Lydian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Meroitic Hieroglyphs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Meroitic Cursive"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kharoshthi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old South Arabian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old North Arabian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Manichaean"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Avestan"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Inscriptional Parthian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Inscriptional Pahlavi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Psalter Pahlavi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Turkic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Hungarian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Hanifi Rohingya"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Rumi Numeral Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Old Sogdian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sogdian"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Elymaic"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Brahmi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kaithi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sora Sompeng"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Chakma"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mahajani"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sharada"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sinhala Archaic Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Khojki"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Multani"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Khudawadi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Grantha"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Newa"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tirhuta"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Siddham"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Modi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mongolian Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Takri"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ahom"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Dogra"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Warang Citi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Nandinagari"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Zanabazar Square"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Soyombo"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Pau Cin Hau"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bhaiksuki"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Marchen"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Masaram Gondi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Gunjala Gondi"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Makasar"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tamil Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cuneiform"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Cuneiform Numbers and Punctuation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Early Dynastic Cuneiform"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Egyptian Hieroglyphs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Egyptian Hieroglyph Format Controls"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Anatolian Hieroglyphs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bamum Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mro"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Bassa Vah"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Pahawh Hmong"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Medefaidrin"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miao"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ideographic Symbols and Punctuation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tangut"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tangut Components"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kana Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Kana Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Small Kana Extension"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Nushu"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Duployan"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Shorthand Format Controls"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Byzantine Musical Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Musical Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ancient Greek Musical Notation"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mayan Numerals"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tai Xuan Jing Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Counting Rod Numerals"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mathematical Alphanumeric Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Sutton SignWriting"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Glagolitic Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Nyiakeng Puachue Hmong"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Wancho"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mende Kikakui"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Adlam"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Indic Siyaq Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ottoman Siyaq Numbers"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Arabic Mathematical Alphabetic Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Mahjong Tiles"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Domino Tiles"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Playing Cards"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Enclosed Alphanumeric Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Enclosed Ideographic Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Miscellaneous Symbols and Pictographs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Emoticons"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Ornamental Dingbats"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Transport and Map Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Alchemical Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Geometric Shapes Extended"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Arrows-C"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplemental Symbols and Pictographs"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Chess Symbols"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Symbols and Pictographs Extended-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension B"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension C"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension D"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension E"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Unified Ideographs Extension F"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("CJK Compatibility Ideographs Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Tags"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Variation Selectors Supplement"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplementary Private Use Area-A"),
    /* TRANSLATORS: You might refer the translations from gucharmap with
                    the following command:
       msgmerge -C gucharmap.po ibus.po ibus.pot */
    N_("Supplementary Private Use Area-B"),
};
#endif
