/* -*- mode: C; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
/* vim:set et sts=4: */
/* ibus - The Input Bus
 * Copyright (C) 2016-2018 Takao Fujiwara <takao.fujiwara1@gmail.com>
 * Copyright (C) 2016 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 */


/* This file is generated by emoji-parser.c. */
include <glib/gi18n.h>

#ifndef __IBUS_EMOJI_GEN_H_
#define __IBUS_EMOJI_GEN_H_
const static char *unicode_emoji_categories[] = {
    N_("Activities"),
    N_("Animals & Nature"),
    N_("Component"),
    N_("Flags"),
    N_("Food & Drink"),
    N_("Objects"),
    N_("People & Body"),
    N_("Smileys & Emotion"),
    N_("Symbols"),
    N_("Travel & Places"),
};
#endif
